### ISSUE TITLE
Records with outlier for layer, do not show outlier information

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#363]
E.g. https://biocache-test.ala.org.au/occurrences/search?q=(lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A435d01a5-7a68-4a24-b220-a7c32ea66b33%20OR%20lsid%3Ahttps%3A%2F%2Fid.biodiversity.org.au%2Ftaxon%2Fapni%2F51311124)%20AND%20basis_of_record%3APRESERVED_SPECIMEN%20AND%20occurrence_date%3A%5B2000-01-01T00%3A00%3A00Z%20TO%202010-01-01T00%3A00%3A00Z%5D&qualityProfile=ALA&fq=outlier_layer_count%3A%222%22

Click on a record in "Records" tab and scroll down to below DwC fields.... there should be a section for Outlier data and a graph being displayed (see [this prod record](https://biocache.ala.org.au/occurrences/3ed01590-d270-490d-9b49-2eed66a1f3f3) for reference) but there is nothing.

EDIT: disabling the DQ profiles, I still see no Outlier data.

**Comment by djtfmartin** [comment]
Fixed in test.

https://biocache-test.ala.org.au/occurrences/f20d9943-44d3-4b66-8a6e-853c8b86e1f7

**Comment by nickdos** [comment]
I see outlier section now but charts are still missing:

![image](https://user-images.githubusercontent.com/532845/120965518-56d27b80-c7a8-11eb-90e8-3251941f66e1.png)

**Comment by nickdos** [comment]
Not a show-stopper so can wait for 1.1 if needed.

**Comment by javier-molina** [comment]
I tried both prod and test and have to reload for  the charts to show:

https://biocache-test.ala.org.au/occurrences/f20d9943-44d3-4b66-8a6e-853c8b86e1f7#outlierInformation

https://biocache.ala.org.au/occurrences/3ed01590-d270-490d-9b49-2eed66a1f3f3

@nickdos would you mind checking if you can reproduce this behaviour?  I  can only guess there is a race condition or similar in biocache-hub.

**Comment by nickdos** [comment]
Yes, now showing for me. I did reload multiple times when testing yesterday, BTW. Suspect JS file was cached.
